### variabili di configurazione per la compilazione ###

USE_DEBUG = yes
USE_CLANG = no
CFLAGS = -DPBC_SUPPORT
LDFLAGS =
LIBS = m gmp nettle hogweed pbc
PROGS = $(basename $(wildcard main.c))
RELEASES = gpl.txt Makefile Makefile.config main.c lib-main.[ch] lib-mesg.[ch] lib-timing.[ch] lib-misc.[ch] 
